M48
; DRILL file KiCad 10.0.4 date 2026-09-19T12:18:25
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-19T12:18:25-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X103.0Y-103.0
X103.0Y-125.0
T2
X153.85Y-102.35
X153.85Y-125.65
X177.65Y-102.35
X177.65Y-125.65
M30
